CREATE TABLE public.address (
    id bigint NOT NULL,
    street character varying(255),
    number VARCHAR(10),
    complement VARCHAR(255),
    neighborhood VARCHAR(255),
    city character varying(255),
    state character varying(255),
    zip_code character varying(255),
    user_id bigint,
    CONSTRAINT address_pkey PRIMARY KEY (id)
);
--
-- Name: addres_id_seq; Type: SEQUENCE; Schema: public; Owner: application
--

ALTER TABLE public.address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.app_user (
    id bigint NOT NULL,
    username character varying(255),
    password character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    email character varying(255)
);


ALTER TABLE public.app_user OWNER TO application;

--
-- Name: app_user_id_seq; Type: SEQUENCE; Schema: public; Owner: application
--

CREATE SEQUENCE public.app_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.app_user_id_seq OWNER TO application;

--
-- Name: app_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: application
--

ALTER SEQUENCE public.app_user_id_seq OWNED BY public.app_user.id;


--
-- Name: category; Type: TABLE; Schema: public; Owner: application
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);
INSERT INTO public.category (id, name) VALUES
(1, 'Analgesics'),
(2, 'Antibiotics'),
(3, 'Antihistamines'),
(4, 'Antacids'),
(5, 'Antidepressants');



ALTER TABLE public.category OWNER TO application;

--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: application
--

CREATE SEQUENCE public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.category_id_seq OWNER TO application;

--
-- Name: category_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: application
--

ALTER SEQUENCE public.category_id_seq OWNED BY public.category.id;


--
-- Name: product; Type: TABLE; Schema: public; Owner: application
--

CREATE TABLE public.product (
    name character varying(255) NOT NULL,
    description character varying(255),
    category_id bigint NOT NULL,
    id bigint NOT NULL,
    price bigint NOT NULL,
    image_url VARCHAR(500)
);

INSERT INTO public.product (id, name, description, category_id, price, image_url) VALUES
(1, 'Paracetamol', 'Pain reliever and fever reducer', 1, 15, '/uploads/products/paracetamol.png'),
(2, 'Ibuprofen', 'NSAID used for pain and inflammation', 1, 18, '/uploads/products/ibuprofen.png'),
(3, 'Calcium Carbonate', 'Used to treat heartburn and indigestion', 4, 8, '/uploads/products/calcium_carbonate.png'),
(4, 'Amoxicillin', 'Broad-spectrum penicillin antibiotic', 2, 35, '/uploads/products/amoxicillin.png'),
(5, 'Azithromycin', 'Macrolide antibiotic for infections', 2, 48, '/uploads/products/azithromycin.png'),
(6, 'Loratadine', 'Non-drowsy allergy medication', 3, 11, '/uploads/products/loratadine.png'),
(7, 'Aspirin', 'Used to reduce pain, fever, or inflammation', 1, 12, '/uploads/products/aspirin.png');


ALTER TABLE public.product OWNER TO application;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: application
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: application
--

CREATE TABLE public.role (
    id integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.role OWNER TO application;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: application
--

CREATE SEQUENCE public.role_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.role_id_seq OWNER TO application;

--
-- Name: role_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: application
--

ALTER SEQUENCE public.role_id_seq OWNED BY public.role.id;


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: application
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id integer NOT NULL
);


ALTER TABLE public.user_roles OWNER TO application;

--
-- Name: app_user id; Type: DEFAULT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.app_user ALTER COLUMN id SET DEFAULT nextval('public.app_user_id_seq'::regclass);


--
-- Name: category id; Type: DEFAULT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.category ALTER COLUMN id SET DEFAULT nextval('public.category_id_seq'::regclass);


--
-- Name: role id; Type: DEFAULT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.role ALTER COLUMN id SET DEFAULT nextval('public.role_id_seq'::regclass);


--
-- Data for Name: app_user; Type: TABLE DATA; Schema: public; Owner: application
--

INSERT INTO public.app_user (id, username, password, first_name, last_name, email ) VALUES
(1, 'k', '$2a$10$mNb9BtaBJY2cA0ntpMGMkeD6pTBT7QxRCTKi1PBgPEw.M7PyQQXE2', 'k', 'k', 'k@k.com');


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: application
--

COPY public.role (id, name) FROM stdin;
1	USER
2	ADMIN
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: application
--

INSERT INTO public.user_roles (user_id, role_id) VALUES (1, 2); -- admin user (id 1) has ADMIN role (id 2)


--
-- Name: app_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: application
--

SELECT pg_catalog.setval('public.app_user_id_seq', 3, true);


--
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: application
--

SELECT pg_catalog.setval('public.category_id_seq', 12, true);


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: application
--

SELECT pg_catalog.setval('public.product_id_seq', 3, true);


--
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: application
--

SELECT pg_catalog.setval('public.role_id_seq', 2, true);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_username_key; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_username_key UNIQUE (username);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: role role_name_key; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_name_key UNIQUE (name);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: product uc_product_name; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT uc_product_name UNIQUE (name);


--
-- Name: category uq_category_name; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uq_category_name UNIQUE (name);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: product fk_product_on_category; Type: FK CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk_product_on_category FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: user_roles user_roles_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;


--
-- Name: user_roles user_roles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: application
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE;

