ALTER TABLE app_user
    ADD CONSTRAINT uc_app_user_email UNIQUE (email);



ALTER TABLE product
ALTER
COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE product
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE role
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));

ALTER TABLE role
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE app_user
    ALTER COLUMN password DROP NOT NULL;



ALTER TABLE app_user
    ALTER COLUMN username DROP NOT NULL;